[package]
name = "image-processing"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1.0"
image = "0.25.5"
rayon = "1.7"
indicatif = "0.17"
anyhow = "^1.0"
num_cpus = "1.15"
imageproc = "0.25.0"
ab_glyph = "^0.2"
